all:
	@echo You are executing \'mk\' command.  Please edit your \'makefile\'.

e:
	@echo You are executing \'e\' command.  Please edit your \'makefile\'.

show:
	@echo You are executing \'show\' command.  Please edit your \'makefile\'.

main:
	@echo You are executing \'main\' command.  Please edit your \'makefile\'.

bk:
	@echo You are executing \'bk\' command.  Please edit your \'makefile\'.

# vim: set filetype=make:
