all:
	@echo You are executing \'mk\' command.  Please edit your \'makefile\'.

e:
	@echo You are executing \'e\' command.  Please edit your \'makefile\'.

show:
	@echo You are executing \'show\' command.  Please edit your \'makefile\'.
